<?php
$hero = !empty($sliders) ? reset($sliders) : array();
$heroEl = !empty($hero['elements']) ? json_decode($hero['elements'], true) : array();
$title = !empty($hero['title']) ? $hero['title'] : 'Run your entire school from one smart workspace.';
$intro = !empty($hero['description']) ? strip_tags($hero['description']) : 'Bring students, staff, learning, finance, and family communication together in one beautifully simple platform.';
$primaryUrl = !empty($heroEl['button_url1']) ? $heroEl['button_url1'] : base_url($cms_setting['url_alias'].'/admission');
$primaryText = !empty($heroEl['button_text1']) ? $heroEl['button_text1'] : 'Get started';
?>
<main class="modern-landing">
<section class="se-hero"><div class="orb one"></div><div class="orb two"></div><div class="container hero-grid">
<div class="hero-copy"><span class="eyebrow"><i></i> The smarter way to manage your school</span><h1><?php echo $title; ?></h1><p><?php echo $intro; ?></p><div class="actions"><a class="se-btn primary" href="<?php echo $primaryUrl; ?>"><?php echo $primaryText; ?> <i class="fas fa-arrow-right"></i></a><a class="se-btn ghost" href="#platform"><i class="fas fa-play"></i> Explore platform</a></div><div class="trust"><div class="avatars"><span>AM</span><span>JO</span><span>SK</span><span>+2k</span></div><p><b>Trusted by growing schools</b><small>Secure, simple, and built for every team</small></p></div></div>
<div class="visual"><div class="float student"><i class="fas fa-user-graduate"></i><span><b>New student</b><small>Enrollment complete</small></span><em>✓</em></div><div class="dashboard"><aside><b><i class="fas fa-shapes"></i></b><i class="fas fa-th-large active"></i><i class="fas fa-user-graduate"></i><i class="fas fa-book-open"></i><i class="fas fa-chart-pie"></i><i class="fas fa-cog"></i></aside><div class="dash-main"><header><span><small>Good morning</small><b>School overview</b></span><i class="far fa-bell"></i></header><div class="mini-stats"><div><i class="fas fa-user-graduate"></i><span><small>Students</small><b>1,248</b></span><em>+8.2%</em></div><div><i class="fas fa-chalkboard-teacher"></i><span><small>Teachers</small><b>84</b></span><em>+4.1%</em></div><div><i class="fas fa-wallet"></i><span><small>Fees</small><b>92%</b></span><em>On track</em></div></div><div class="charts"><div class="chart"><header><b>Attendance</b><small>This week</small></header><div class="bars"><i style="height:52%"></i><i style="height:74%"></i><i style="height:62%"></i><i style="height:88%"></i><i style="height:78%"></i><i style="height:92%"></i><i style="height:84%"></i></div></div><div class="performance"><b>Performance</b><div class="ring">87%</div><small>Excellent progress</small></div></div><div class="activity"><header><b>Recent activity</b><small>View all</small></header><p><i class="fas fa-file-alt"></i><span><b>Report cards published</b><small>Grade 8 - 12 minutes ago</small></span><em>Completed</em></p><p><i class="fas fa-bus"></i><span><b>Bus route updated</b><small>Route B - 28 minutes ago</small></span><em>Updated</em></p></div></div></div><div class="float attendance"><strong>96%</strong><span><b>Attendance</b><small>Today's average</small></span></div></div>
</div></section>
<section class="features" id="platform"><div class="container"><div class="section-head"><div><span class="kicker">ONE CONNECTED PLATFORM</span><h2>Everything your school needs.<br><em>Nothing it doesn't.</em></h2></div><p>Purpose-built tools that save your team time, give leaders clarity, and help every learner thrive.</p></div><div class="feature-grid"><?php foreach(array_slice($features,0,4) as $key=>$value){$el=json_decode($value['elements'],true);?><article class="feature-card c<?php echo $key+1;?>"><span><i class="<?php echo $el['icon'];?>"></i></span><h3><?php echo $value['title'];?></h3><p><?php echo strip_tags($value['description']);?></p><a href="<?php echo $el['button_url'];?>"><?php echo $el['button_text'];?> <i class="fas fa-arrow-right"></i></a></article><?php }?></div></div></section>
<?php if(!empty($wellcome)){$welcomeEl=json_decode($wellcome['elements'],true);?><section class="story"><div class="container story-grid"><div class="story-visual"><img src="<?php echo base_url('uploads/frontend/home_page/'.$welcomeEl['image'].img_reload());?>" alt="School community"><div class="story-stat"><b>40%</b><span>less time spent<br>on admin work</span></div></div><div class="story-copy"><span class="kicker">BUILT AROUND YOUR SCHOOL</span><h2><?php echo $wellcome['title'];?></h2><h4><?php echo $wellcome['subtitle'];?></h4><div class="richtext"><?php echo nl2br($wellcome['description']);?></div><div class="checks"><span><i class="fas fa-check"></i> One source of truth</span><span><i class="fas fa-check"></i> Less repetitive work</span><span><i class="fas fa-check"></i> Better family engagement</span><span><i class="fas fa-check"></i> Insights that drive action</span></div><a class="text-link" href="<?php echo base_url($cms_setting['url_alias'].'/about');?>">Discover our approach <i class="fas fa-arrow-right"></i></a></div></div></section><?php }?>
<?php if(!empty($services)){?><section class="modules"><div class="container"><div class="center-head"><span class="kicker">POWERFUL, YET SIMPLE</span><h2><?php echo $services['title'];?></h2><p><?php echo strip_tags($services['description']);?></p></div><div class="module-grid"><?php $this->db->where('branch_id',$branchID);$list=$this->db->get('front_cms_services_list')->result_array();foreach($list as $value){?><div class="module"><span><i class="<?php echo $value['icon'];?>"></i></span><div><h4><?php echo $value['title'];?></h4><p><?php echo $value['description'];?></p></div></div><?php }?></div></div></section><?php }?>
<?php if(!empty($statistics)){$stats=json_decode($statistics['elements'],true);?><section class="impact"><div class="container"><div><span class="kicker">REAL IMPACT, EVERY DAY</span><h2><?php echo $statistics['title'];?></h2><p><?php echo strip_tags($statistics['description']);?></p></div><div class="impact-grid"><?php for($i=1;$i<5;$i++){?><div><i class="<?php echo $stats['widget_icon_'.$i];?>"></i><strong><span class="counter" data-count="<?php echo $this->home_model->getStatisticsCounter($stats['type_'.$i],$branchID);?>">0</span>+</strong><small><?php echo $stats['widget_title_'.$i];?></small></div><?php }?></div></div></section><?php }?>
<?php if(!empty($testimonial)){$this->db->where('branch_id',$branchID);$testimonials=$this->db->get('front_cms_testimonial')->result_array();?><section class="testimonials"><div class="container"><div class="center-head"><span class="kicker">LOVED BY SCHOOL COMMUNITIES</span><h2><?php echo $testimonial['title'];?></h2><p><?php echo strip_tags($testimonial['description']);?></p></div><div class="testimonial-grid"><?php foreach(array_slice($testimonials,0,3) as $value){?><article><div class="stars"><?php for($i=1;$i<6;$i++)echo '<i class="'.($i<=$value['rank']?'fas':'far').' fa-star"></i>';?></div><blockquote>“<?php echo strip_tags($value['description']);?>”</blockquote><div class="person"><img src="<?php echo $this->testimonial_model->get_image_url($value['image']);?>" alt=""><span><b><?php echo $value['name'];?></b><small><?php echo $value['surname'];?></small></span></div></article><?php }?></div></div></section><?php }?>
<?php $ctaEl=!empty($cta_box['elements'])?json_decode($cta_box['elements'],true):array();?><section class="final-cta"><div class="container"><div class="cta-card"><div><span class="kicker">READY WHEN YOU ARE</span><h2><?php echo !empty($cta_box['title'])?$cta_box['title']:'Make every school day work better.';?></h2><p>Join a new generation of schools replacing busywork with meaningful progress.</p></div><a class="se-btn light" href="<?php echo !empty($ctaEl['button_url'])?$ctaEl['button_url']:$primaryUrl;?>"><?php echo !empty($ctaEl['button_text'])?$ctaEl['button_text']:'Book a free demo';?> <i class="fas fa-arrow-right"></i></a></div></div></section>
</main>
